services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mqtt_client/certificates:/mosquitto/config/certs

  influxdb:
    image: influxdb:2.6
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=default
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token123
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  api:
    build: ./api
    env_file: ./api/.env
    depends_on:
      - mosquitto
      - influxdb
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  influxdb-data: